#define LUM_WEIGHTS float3(0.27f, 0.67f, 0.06f)
#define MIDDLE_GREY 0.08f
#define BLOOM_THRESHOLD 0.5f
#define BLOOM_MULTIPLIER	0.6f
#define GAMMA_POW 2.2
#define DELTA 0.00000001f
#define BLURH_THREADS_X 4
#define BLURH_THREADS_Y 64
#define BLURV_THREADS_X 64
#define	BLURV_THREADS_Y 4
#define ADD_THREADS_X 64
#define ADD_THREADS_Y 2
#define LUM_AND_BRIGHT_THREADS 8u
#define REDUCE_GROUP_SIZE 64
#define GET_AVG_LUM_THREADS 16u
#define REDUCE_Y_PER_THREAD 8
